# Generated by Django 4.0.4 on 2022-05-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sub_categoria', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
    ]
